### ISSUE TITLE
Request horizon of the prediction attribute in Holt Smoothing predict function

### ISSUE THREAD

**Issue by 1Jesper1** [antoinevastel/zodiac-ts#1]
I would like to pass a horizon of the prediction to the Holt Smoothing method like possible for the Double Exponential Smoothing method (Brown's?).

**Comment by antoinevastel** [comment]
I'll take a look at it and come back to you soon.

**Comment by antoinevastel** [comment]
I made the change and added an horizon parameter to the method.
